ericanderson/osdk-ts

- .github/workflows/release.yml
- .monorepolint.config.mjs
- package.json
- packages/api/package.json
- pnpm-lock.yaml
Tweaks to support publishing snapshots
* Hoist internal packages so they aren't listed as dev-dependencies
* Provide the release workflow access to the GITHUB_TOKEN for creating the release PR.
> Hoist monorepo internal packages so we can publish a snapshot

- .changeset/config.json
- .github/workflows/release.yml
- .gitignore
- .monorepolint.config.mjs
- dprint.json
- examples/basic/cli/package.json
- examples/basic/cli/tsconfig.json
- examples/basic/cli/tsup.json
- examples/basic/sdk/package.json
- examples/basic/sdk/tsconfig.json
- monorepo/eslint-config-sane/library.cjs
- monorepo/mytsup/tsup.mjs
- package.json
- packages/api/package.json
- packages/api/tsconfig.json
- pnpm-lock.yaml
- turbo.json
* `turbo dev` provides better output and is more efficient for type checking
* (hopefully) snapshots are now published with the correct version and the npm tag `next`
> Workflow improvements

- examples/basic/cli/src/examples/fetchAggregationForEmployees.ts
- examples/basic/cli/src/examples/fetchAggregationForEmployeesGrouped.ts
- examples/basic/cli/src/examples/fetchAggregationForEmployeesGroupedThin.ts
- examples/basic/cli/src/examples/fetchEmployeeLead.ts
- examples/basic/cli/src/examples/fetchEmployeePage.ts
- examples/basic/cli/src/examples/fetchEmployeePageThin.ts
- examples/basic/cli/src/index.ts
- examples/basic/cli/src/typeChecks.ts
- packages/api/src/client/object/aggregateOrThrow.test.ts
- packages/api/src/client/query/aggregations/AggregationResultsWithoutGroups.ts
Provides some sanity that we don't break the derived type APIs when we make changes.
We will need to keep adding to this as we discover new issues and implement new features.
**Bonus:** Doing this helped expose + fix properties showing up in intellisense as `adUsername: never` for aggregations instead of just omitting it. This PR also fixes that.
> Implement type tests for existing code

- .vscode/settings.json
- packages/generator/src/v1.1/generateClientSdkVersionOneDotOne.test.ts
- packages/generator/src/v1.1/generateClientSdkVersionOneDotOne.ts
- packages/generator/src/v1.1/generateFoundryClient.test.ts
- packages/generator/src/v1.1/generateFoundryClient.ts
- packages/generator/src/v1.1/generateMetadata.test.ts
- packages/generator/src/v1.1/generateMetadata.ts
- packages/legacy-client/src/client/foundryClient.ts
- packages/legacy-client/src/client/foundryClientOptions.ts
- packages/legacy-client/src/client/index.ts
- packages/legacy-client/src/client/ontology.test.ts
- packages/legacy-client/src/client/ontology.ts
- packages/legacy-client/src/index.ts
- packages/legacy-client/src/metadata/OntologyDefinition.ts
- packages/legacy-client/src/metadata/index.ts
- packages/legacy-client/src/util/test/index.ts
- packages/legacy-client/src/util/test/mockOntology.ts
Adds stubs for `FoundryClient` and generating a back-compat interface. 
Here we're using a generated client to instantiate with the correct types from the metadata.
> Adding stubs for FoundryClient for backcompat

- packages/legacy-client/src/client/convertWireToOsdkObject.ts
- packages/legacy-client/src/ontology-runtime/baseTypes/SingleLinkImpl.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/ErrorHandlers.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/Errors.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/OntologyProvider.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/calls/ClientContext.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/calls/getLinkedObject.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/calls/getLinkedObjectsPage.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/calls/listLinkedObjects.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/calls/util/ResponseCreators.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/calls/util/wrapResult.ts
- packages/legacy-client/src/ontology-runtime/ontologyProvider/errors/GetLinkedObjectErrorHandler.ts
Lots of underneath the hood code churn to implement a relatively straightforward `SingleLinkImpl` class.
- Introduce `ClientContext` which is the object that gets passed around internally to preserve the information required to actually perform network requests.
- Add `ObjectsExceeded` to GetLinkedObjectError in order to make GetLinkedObjectsError assignable
- Start breaking out OntologyProvider into individual methods
- Rework of `getLinkedObject` logic in order to fix compile errors that were not found in the older implementation.
Skipping any refactoring of the error handling for now, we can do that in a later PR.
> SingleLinkImpl

- packages/api/src/client/createOpenApiRequest.test.ts
- packages/api/src/client/createOpenApiRequest.ts
- packages/api/src/client/internal/net/index.ts
- packages/api/src/client/object/aggregateOrThrow.ts
- packages/api/src/client/object/fetchPageOrThrow.ts
- packages/api/src/index.ts
- packages/legacy-client/src/ontology-runtime/aggregations/aggregationConverters.ts
- Move createOpenApiRequest out of the internal/net directory
- Remove exports of other internal/net types and used the types in @osdk/legacy-client instead
> Clean up @osdk/api 'internal' exports

- packages/legacy-client/src/client/convertWireToOsdkObject.test.ts
- packages/legacy-client/src/client/convertWireToOsdkObject.ts
- packages/legacy-client/src/client/objectSets/createCachedOntologyTransform.ts
- packages/legacy-client/src/client/objectSets/createObjectSetAggregationStep.ts
Add `createCachedOntologyTransform` that gives us an easy shorthand to defer and cache computation from `ObjectDefinition -> T`.
Use this for the object prototypes, and the aggregatable, groupable, multipleAggregation properties.
I can add this to the orderBy and searchFilter code as well if we like this direction.
> Standardize caching

- packages/legacy-client/src/client/actions.test.ts
- packages/legacy-client/src/client/objectSets/OsdkObjectSet.test.ts
- packages/legacy-client/src/client/objectSets/createCachedOntologyTransform.ts
- packages/legacy-client/src/client/objects/convertWireToOsdkObject.ts
- packages/legacy-client/src/util/test/mocks/mockObjects.ts
Caching the object prototypes with an implied client means that multiple clients for the same ontology could accidentally use the incorrect client.
Instead we use the same prototype but pass through the ThinClient reference as a non-enumerable symbol on the object itself.
> Rework convertWireToOsdkObject caching

- examples/one_dot_one/src/generatedNoCheck/Ontology.ts
- examples/one_dot_one/src/generatedNoCheck/ontology/actions/Actions.ts
- examples/one_dot_one/src/generatedNoCheck/ontology/objects/Objects.ts
- examples/one_dot_one/src/generatedNoCheck/ontology/queries/Queries.ts
- packages/generator/src/v1.1/generateActions.test.ts
- packages/generator/src/v1.1/generateActions.ts
- packages/generator/src/v1.1/generateClientSdkVersionOneDotOne.ts
- packages/generator/src/v1.1/generateMetadataFile.test.ts
- packages/generator/src/v1.1/generateMetadataFile.ts
- packages/generator/src/v1.1/generateObjectsInterfaceFile.test.ts
- packages/generator/src/v1.1/generateObjectsInterfaceFile.ts
- packages/generator/src/v1.1/generateQueries.test.ts
- packages/generator/src/v1.1/generateQueries.ts
To match the older package layout a little more closely
> Relocate ontology(Actions|Queries|Objects) into their respective directories

- .github/workflows/ci.yml
Omitting 16 on purpose because it is no longer receiving security updates, and some of the tests depend on the [native fetch](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) implementation.
> Check builds with node 18, 20, and 21

- .monorepolint.config.mjs
- examples/basic/cli/tsconfig.json
- examples/basic/sdk/tsconfig.json
- examples/one_dot_one/package.json
- examples/one_dot_one/tsconfig.json
- packages/api/src/ontology/index.ts
- packages/api/tsconfig.json
- packages/cli/tsconfig.json
- packages/client/tsconfig.json
- packages/gateway/tsconfig.json
- packages/generator/src/v1.1/generatePerActionDataFiles.ts
- packages/generator/src/v2.0/generateClientSdkVersionTwoPointZero.test.ts
- packages/generator/tsconfig.json
- packages/legacy-client/src/client/objects/convertWireToOsdkObject.ts
- packages/legacy-client/src/client/ontology.ts
- packages/legacy-client/src/client/queryProxy.ts
- packages/legacy-client/src/client/utils/index.ts
- packages/legacy-client/tsconfig.json
- pnpm-lock.yaml
- Change examples/one_dot_one to use ts4.9
- Fix errors coming from api, generator, and legacy-client related to the old compiler
> Typescript 4.9 support for v1.1 code

- .changeset/popular-snakes-pretend.md
- packages/generator/src/util/commaSeparatedIdentifiers.ts
- packages/generator/src/util/commaSeparatedTypeIdentifiers.ts
- packages/generator/src/v1.1/generateMetadataFile.test.ts
- packages/generator/src/v1.1/generateMetadataFile.ts
Just suffix `Action` or `Query` to make them unique again
> Protect against duplicate identifiers across object, query, and action names

- .changeset/new-kings-destroy.md
- packages/generator/src/v1.1/generateQueries.ts
Objects are always hydrated even if the backend returns only a PK in the query response
> Fix generated query return type

- packages/cli/package.json
- packages/cli/src/commands/typescript/generate/TypescriptGenerateArgs.ts
- packages/cli/src/commands/typescript/generate/generate.ts
- packages/cli/src/commands/typescript/generate/handleGenerate.mts
- packages/cli/tsconfig.json
- packages/client/src/objectSet/ObjectSetListenerWebsocket.ts
- pnpm-lock.yaml
Adds the ability to generate an ontology directly from a given stack, given its stack URL and a clientId.
Users can still generate from a json file if they prefer.
> Allow direct connection to a stack for ontology generation

- packages/cli/src/commands/auth/login/loginFlow.ts
- packages/cli/src/commands/typescript/generate/TypescriptGenerateArgs.ts
- packages/cli/src/commands/typescript/generate/generate.ts
- packages/cli/src/commands/typescript/generate/handleGenerate.mts
- The code generation command now optionally writes the json to disk for hand-modification
- The CLI will now detect if the authentication process is taking too long and prompt the user with the URL
- If the ontology fetch fails, we prompt with the underlying reason if one exists, like for invalid cert
> Small CLI cleanups from usability feedback

- .changeset/cold-carrots-dream.md
- packages/legacy-client/src/client/actions/actions.test.ts
- packages/legacy-client/src/client/actions/createActionProxy.ts
- packages/legacy-client/src/client/ontology.test.ts
- packages/legacy-client/src/client/ontology.ts
- packages/legacy-client/src/client/queries.test.ts
- packages/legacy-client/src/client/queryProxy.ts
When we moved to the proxy-based implementation with v1.1 it accidentally removed the ability for us to inspect what types that we had compiled in.
> Add objects, actions, queries enumerability for backcompat

- .changeset/ninety-guests-shake.md
- packages/foundry-sdk-generator/src/generate/betaClient/generatePackageJson.ts
This was causing errors of the flavor:
```
ERROR in ./src/pages/home.tsx 4:0-61
Module not found: Error: Default condition should be last one
@ ./src/app.tsx 4:0-40 16:45-53
ERROR in ./src/utils/client.ts 2:0-69
Module not found: Error: Default condition should be last one
@ ./src/pages/authCallback.tsx 4:0-41 13:8-14:19
@ ./src/app.tsx 5:0-52 27:37-49
webpack 5.82.1 compiled with 2 errors in 1939 ms
```
> Fix incorrect order of exports in generated package.json

- packages/client/src/Definitions.ts
- packages/client/src/object/Attachment.ts
- packages/client/src/object/ObjectDefinitions.test.ts
- packages/client/src/object/convertWireToOsdkObjects.test.ts
- packages/client/src/object/convertWireToOsdkObjects.ts
- packages/shared.test/src/stubs/objectSetRequest.ts
- packages/shared.test/src/stubs/objects.ts
In order to be able to serialize Attachments for Actions, we need to be able to differentiate them when we convert to the wire spec. `{rid: string}` is probably not specific enough to safely create these payloads so we promote it to a full class instead.
legacy-client also added additional methods on the Attachments class to get metadata and then the actual data itself, but that is omitted from this PR.
This also improves our msw stubs to handle more of the `objectTypeWithAllPropertyTypes` objects.
> Add Attachments class to v2

- packages/client/src/Client.ts
- packages/client/src/createClient.ts
- packages/client/src/objectSet/ObjectSet.ts
- packages/client/src/objectSet/createObjectSet.ts
This syntax was possible to write, but was not correctly implemented.
```typescript
client.objectSet("Employee", {$where: {"employeeId": 12}})
```
Removing for clarity around how to create filtering object sets.
> Remove ObjectSetOptions

- .changeset/empty-roses-confess.md
- packages/client/src/query/WhereClause.ts
- this is only a type change because the underlying implementation already supports generic { fooFilterType: value } style queries
> Add where clause support for "contains" filter

- .changeset/red-keys-repeat.md
- packages/foundry-sdk-generator/src/__e2e_tests__/loadObjects.test.ts
- packages/foundry-sdk-generator/src/__e2e_tests__/search.test.ts
- packages/legacy-client/src/client/baseTypes/localDate.ts
- packages/legacy-client/src/client/baseTypes/timestamp.ts
We moved dateTime from typescript private to #private, which changed the enforcement semantics. This change puts it back to the original implementation.
> Fix LocalDate/Timestamp unintentional backcompat break

- .changeset/fast-taxis-behave.md
- packages/foundry-sdk-generator/src/ontologyMetadata/ontologyMetadataResolver.ts
Check server's metadata to make sure it isn't an error before we start operating on it.
Suspect that this might be hiding some of the root causes for build failures we've had in the past.
> Better foundry-sdk-generator error handling
